# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrandNew' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BrandNew
	pod 'PocServices', :path => "../POCServices/"

  target 'BrandNewTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
